error_dict = {
    0 : 'OnlyAtomError: Molecule consists only of one atom, thus further procedure is unnecessary.\n',
    1 : 'AddingHydrogenError: H atoms could not be added via AddHs.\n',
    2 : 'JobTypeNoneError: In jm_functions.execute_job(), no job type was obtained.\n',
    3 : 'DEPRECATED!EmbeddingNoneError: get_embedded_conformer neither returned mol nor smiles.\n',
    4 : 'RdkJobError: An unknown error occured during the rdkit job.\n',
    5 : 'NoRdkXyzError: No xyz file was written at the end of the rdk routine.\n',
    6 : 'XtbCheckError: No normal termination of xtb or no crest_best.xyz existing.\n',
    7 : 'DftRunningError: Trc file contradicts slurm list. Stated running for dft, but no calc was found, thus all was traced as failed.\n',
    8 : 'DftResultsError: analyze_dft_results gave failed as status.\n',
    9 : 'AnalysisCanceledError: No analysis was possible due to some other error before.\n',
    10: 'ExtractionError: An error occured during the extraction of results to json.\n',
    11: 'LogOpenError: Log file could not be read.\n',
    12: 'NoSMILESError: No SMILES code was found for the given DDB No.\n',
    13: 'TrcCorruptedError: trc file couldnt not be read.\n',
    14: 'RdkitDescError: Rdkit descriptors could not be obtained.\n',
    15: 'JSONInitError: The json dictionary for results could not be initialized.\n',
    16: 'DFTNotConvergedError: DFT calculation did not converge.\n',
    17: 'AnalysisError: Ana module could not obtain any results from calculations.\n',
    18: 'SMILESConvertionError: SMILES code could not be converted to mol object.\n',
    19: 'IonicSMILESError: Compound is ionic, thus no further considerations are made.\n',
    20: 'NonStringSMILESError: SMILES is not a string, thus corrupted.\n',
    21: 'IsotopeError: SMILES seem to obtain isotopes. During handling of this, an error occured.\n',
    22: 'XTBRuntimeViolationError: XTB will probably take too long. Procedure was denied.\n',
    23: 'DFTRuntimeViolationError: DFT will probably take too long. Procedure was denied.\n'
}